FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/auth

COPY ./requirements.txt /usr/src/auth/requirements.txt

RUN pip install -r requirements.txt

COPY . /usr/src/auth

ENV FLASK_ENV=development